-- Write your query below and then click "Run Query" to execute it. To save multiple queries, click the "+" icon on the left.
/*
CREATE TRIGGER trg_line_total 
BEFORE INSERT ON LINE FOR EACH ROW
  SET NEW.LINE_TOTAL = NEW.LINE_UNITS * NEW.LINE_PRICE;

UPDATE PRODUCT SET P_QOH = 26 WHERE P_CODE = '13-Q2/P2';/*
CREATE TRIGGER trg_line_prod
AFTER INSERT ON LINE FOR EACH ROW
  UPDATE PRODUCT SET P_QOH = P_QOH - NEW.LINE_UNITS WHERE NEW.P_CODE = PRODUCT.P_CODE;

UPDATE PRODUCT SET P_QOH = 13 WHERE P_CODE = '13-Q2/P2';

DELIMITER $$

CREATE PROCEDURE prc_inv_amounts(IN IN_NUM INT)
BEGIN
  DECLARE subtotal, tax, total DEC(10,2) DEFAULT 0.0;
  SELECT SUM(LINE_TOTAL) INTO subtotal FROM LINE 
  WHERE INV_NUMBER = IN_NUM;
  SET tax = subtotal * .08;
  SET total = subtotal + tax;
  UPDATE INVOICE SET INV_SUBTOTAL = subtotal WHERE INV_NUMBER = IN_NUM;
  UPDATE INVOICE SET INV_TAX = tax WHERE INV_NUMBER = IN_NUM;
  UPDATE INVOICE SET INV_TOTAL = total WHERE INV_NUMBER = IN_NUM;
END $$

DELIMETER ;
*/
DROP PROCEDURE prc_cus_balance_update;

DELIMITER $$

CREATE PROCEDURE prc_cus_balance_update(IN IN_NUM INT)
BEGIN
  DECLARE total DEC(10,2) DEFAULT 0.0;
  DECLARE ccode INT DEFAULT 0;
  SELECT INV_TOTAL, CUS_CODE INTO total, ccode FROM INVOICE 
  WHERE INV_NUMBER = IN_NUM;
  UPDATE CUSTOMER SET CUS_BALANCE = CUS_BALANCE + total WHERE CUS_CODE = ccode;
END $$
DELIMETER ;
