CREATE VIEW RECLEAGUE.CONTEST_RESULTS AS
SELECT CI.CONTEST_ID, CI.CONTEST_NAME, TE.TEAM_NAME, TE.TEAM_ID, SUM(EV.LEAGUE_POINTS) AS CONTEST_TOTAL
FROM RECLEAGUE.EVENTS EV
INNER JOIN RECLEAGUE.CONTESTS CO
ON EV.EVENT_ID = CO.EVENT_ID
INNER JOIN RECLEAGUE.TEAMS TE
ON EV.TEAM_ID = TE.TEAM_ID
INNER JOIN RECLEAGUE.CONTEST_INFO CI
ON CO.CONTEST_ID = CI.CONTEST_ID
GROUP BY TE.TEAM_ID, TE.TEAM_NAME, CI.CONTEST_ID, CI.CONTEST_NAME
ORDER BY CI.CONTEST_ID, CONTEST_TOTAL DESC;