CREATE VIEW RECLEAGUE.CONTEST_WINNERS AS
SELECT CONTEST_NAME, CONTEST_ID, TEAM_NAME, TEAM_ID, CONTEST_TOTAL
FROM(
	SELECT CONTEST_NAME, CONTEST_ID, TEAM_NAME, TEAM_ID, CONTEST_TOTAL,
	MAX(CONTEST_TOTAL) OVER (PARTITION BY CONTEST_ID) AS POINTS
	FROM RECLEAGUE.CONTEST_RESULTS
)
WHERE CONTEST_TOTAL = POINTS;