CREATE TABLE B2B.EMPLOYEES 
   (	
    EID NUMBER(6,0), 
	FNAME VARCHAR2(15) NOT NULL, 
	LNAME VARCHAR2(15) NOT NULL, 
	SSN NUMBER(9,0) NOT NULL, 
	DEPT VARCHAR2(15) NOT NULL, 
	TITLE VARCHAR2(15) NOT NULL, 
	SALARY NUMBER(7,2), 
	 PRIMARY KEY (EID)
   )