CREATE TABLE RECLEAGUE.CONTEST_INFO(
	CONTEST_ID NUMBER(6) PRIMARY KEY,
	CONTEST_NAME VARCHAR2(40) NOT NULL,
	DESCRIPTION VARCHAR2(1000)
);

CREATE TABLE RECLEAGUE.CONTESTS(
	EVENT_ID NUMBER(9) NOT NULL,
	CONTEST_ID NUMBER(6) NOT NULL,
	CONSTRAINT CONTESTS_INFO_FK
		FOREIGN KEY (CONTEST_ID)
		REFERENCES RECLEAGUE.CONTEST_INFO(CONTEST_ID),
	CONSTRAINT CONTESTS_EVENTS_FK
		FOREIGN KEY (EVENT_ID)
		REFERENCES RECLEAGUE.EVENT_INFO(EVENT_ID),		
	CONSTRAINT PK_CONTESTS
		PRIMARY KEY (CONTEST_ID, EVENT_ID)
);

CREATE SEQUENCE contest_seq
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 999999
	CYCLE;