CREATE TABLE RECLEAGUE.TEAM_MEMBERS(
	TEAM_ID NUMBER(6) NOT NULL,
	MEMBER_NAME VARCHAR2(16) NOT NULL,
	EMAIL VARCHAR2(25) NOT NULL,
	CONSTRAINT FK_TEAM
		FOREIGN KEY (TEAM_ID)
		REFERENCES RECLEAGUE.TEAMS(TEAM_ID),
	CONSTRAINT PK_TEAM
		PRIMARY KEY (TEAM_ID, MEMBER_NAME)
);