CREATE TABLE TEAM_MEMBERS(
  TEAMID      NUMBER(6) NOT NULL,
  EID         NUMBER(6) NOT NULL,
    CONSTRAINT FK_EMPLOYEE
      FOREIGN KEY(EID) REFERENCES EMPLOYEES(EID)
  );
  
ALTER TABLE TEAM_MEMBERS
ADD CONSTRAINT FK_TEAM FOREIGN KEY(TEAMID) REFERENCES TEAM_INFO(TEAMID);