CREATE TABLE RECLEAGUE.TEAMS(
	TEAM_ID NUMBER(6) PRIMARY KEY,
	TEAM_NAME VARCHAR2(20) NOT NULL,
	CAPTAIN VARCHAR2(10)
);

CREATE TABLE RECLEAGUE.TEAM_MEMBERS(
	TEAM_ID NUMBER(6) NOT NULL,
	MEMBER_NAME VARCHAR2(16) NOT NULL,
	EMAIL VARCHAR2(25) NOT NULL,
	CONSTRAINT FK_TEAM
		FOREIGN KEY (TEAM_ID)
		REFERENCES RECLEAGUE.TEAMS(TEAM_ID),
	CONSTRAINT PK_TEAM
		PRIMARY KEY (TEAM_ID, MEMBER_NAME)
);

CREATE SEQUENCE team_seq
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 999999
	CYCLE;