INSERT INTO RECLEAGUE.CONTESTS(CONTEST_ID, EVENT_ID) VALUES (1, 1);
INSERT INTO RECLEAGUE.CONTESTS(CONTEST_ID, EVENT_ID) VALUES (1, 2);
INSERT INTO RECLEAGUE.CONTESTS(CONTEST_ID, EVENT_ID) VALUES (1, 3);
INSERT INTO RECLEAGUE.CONTESTS(CONTEST_ID, EVENT_ID) VALUES (2, 4);
INSERT INTO RECLEAGUE.CONTESTS(CONTEST_ID, EVENT_ID) VALUES (2, 5);
INSERT INTO RECLEAGUE.CONTESTS(CONTEST_ID, EVENT_ID) VALUES (2, 6);
commit;
