INSERT INTO RECLEAGUE.TEAM_MEMBERS(Team_ID, Member_name, email) VALUES (1,'LeBron','goat@cavs.com');
INSERT INTO RECLEAGUE.TEAM_MEMBERS(Team_ID, Member_name, email) VALUES (1,'Love', 'love@cavs.com');
INSERT INTO RECLEAGUE.TEAM_MEMBERS(Team_ID, Member_name, email) VALUES (1,'Kyrie','flat@cavs.com');
INSERT INTO RECLEAGUE.TEAM_MEMBERS(Team_ID, Member_name, email) VALUES (1,'JR Smith','pipe@cavs.com');
INSERT INTO RECLEAGUE.TEAM_MEMBERS(Team_ID, Member_name, email) VALUES (2,'Mario','mario@nintendo.com');
INSERT INTO RECLEAGUE.TEAM_MEMBERS(Team_ID, Member_name, email) VALUES (2,'Luigi','sadbro@nintendo.com');
INSERT INTO RECLEAGUE.TEAM_MEMBERS(Team_ID, Member_name, email) VALUES (2,'Link','hya@nintendo.com');
INSERT INTO RECLEAGUE.TEAM_MEMBERS(Team_ID, Member_name, email) VALUES (2,'Yoshi','dino@nintendo.com');
INSERT INTO RECLEAGUE.TEAM_MEMBERS(Team_ID, Member_name, email) VALUES (2,'Zelda','princess@nintendo.com');
INSERT INTO RECLEAGUE.TEAM_MEMBERS(Team_ID, Member_name, email) VALUES (3,'Burger','burg@foodies.com');
INSERT INTO RECLEAGUE.TEAM_MEMBERS(Team_ID, Member_name, email) VALUES (3,'Strudel','strude@foodies.com');
INSERT INTO RECLEAGUE.TEAM_MEMBERS(Team_ID, Member_name, email) VALUES (3,'Sushi','sushi@foodies.com');
commit;